# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.setEnabled(True)
        MainUI.resize(1297, 644)
        MainUI.setStyleSheet("background-image: url(:/images/bg01_cs02.png);\n"
"")
        # 禁用最大化按钮
        self.setWindowFlags(Qt.Window | Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)
        self.bg = QtWidgets.QGroupBox(MainUI)
        self.bg.setEnabled(True)
        self.bg.setGeometry(QtCore.QRect(300, 10, 1001, 651))
        self.bg.setStyleSheet("")
        self.bg.setObjectName("bg")
        self.frame = QtWidgets.QFrame(self.bg)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(9, 14, 981, 201))
        self.frame.setStyleSheet("background: transparent;  ")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.resetView_1 = QtWidgets.QPushButton(self.frame)
        self.resetView_1.setGeometry(QtCore.QRect(850, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.resetView_1.setFont(font)
        self.resetView_1.setStyleSheet("#resetView_1{\n"
"    background:transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#resetView_1:hover{\n"
"    icon:url(images/refresh_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#resetView_1:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetView_1.setIcon(icon)
        self.resetView_1.setObjectName("resetView_1")
        self.gridFrame_2 = QtWidgets.QFrame(self.frame)
        self.gridFrame_2.setGeometry(QtCore.QRect(0, 110, 841, 81))
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tip5 = QtWidgets.QPushButton(self.gridFrame_2)
        self.tip5.setStyleSheet("#tip5{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip5:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip5:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tip5.setIcon(icon1)
        self.tip5.setObjectName("tip5")
        self.horizontalLayout_4.addWidget(self.tip5)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.textView_3 = QtWidgets.QTextEdit(self.gridFrame_2)
        self.textView_3.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.textView_3.setFont(font)
        self.textView_3.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textView_3.setObjectName("textView_3")
        self.horizontalLayout_4.addWidget(self.textView_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tip6 = QtWidgets.QPushButton(self.gridFrame_2)
        self.tip6.setStyleSheet("#tip6{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip6:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip6:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip6.setText("")
        self.tip6.setIcon(icon1)
        self.tip6.setObjectName("tip6")
        self.horizontalLayout_5.addWidget(self.tip6)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.textView_4 = QtWidgets.QTextEdit(self.gridFrame_2)
        self.textView_4.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.textView_4.setFont(font)
        self.textView_4.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textView_4.setObjectName("textView_4")
        self.horizontalLayout_5.addWidget(self.textView_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.frame)
        self.gridFrame_3.setGeometry(QtCore.QRect(0, 30, 841, 81))
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tip3 = QtWidgets.QPushButton(self.gridFrame_3)
        self.tip3.setStyleSheet("#tip3{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip3:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip3.setText("")
        self.tip3.setIcon(icon1)
        self.tip3.setObjectName("tip3")
        self.horizontalLayout_2.addWidget(self.tip3)
        self.label_2 = QtWidgets.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textView_1 = QtWidgets.QTextEdit(self.gridFrame_3)
        self.textView_1.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.textView_1.setFont(font)
        self.textView_1.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textView_1.setObjectName("textView_1")
        self.horizontalLayout_2.addWidget(self.textView_1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tip4 = QtWidgets.QPushButton(self.gridFrame_3)
        self.tip4.setStyleSheet("#tip4{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip4:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip4:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip4.setText("")
        self.tip4.setIcon(icon1)
        self.tip4.setObjectName("tip4")
        self.horizontalLayout_3.addWidget(self.tip4)
        self.label_3 = QtWidgets.QLabel(self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textView_2 = QtWidgets.QTextEdit(self.gridFrame_3)
        self.textView_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.textView_2.setFont(font)
        self.textView_2.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textView_2.setObjectName("textView_2")
        self.horizontalLayout_3.addWidget(self.textView_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
" margin-bottom: 5px;")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.bg)
        self.frame_3.setGeometry(QtCore.QRect(10, 240, 981, 391))
        self.frame_3.setStyleSheet("background: transparent;  ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 921, 341))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::tab-bar { \n"
"    alignment: center; \n"
"} \n"
"QTabBar::tab:hover{ \n"
"    color:  rgb(0, 0, 0);\n"
"    background-color: transparent;\n"
"}\n"
"QTabWidget::pane{ \n"
"    border:none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: transparent; /* 标签页背景颜色 */\n"
"    color: rgb(186, 186, 186); /* 标签页字体颜色 */\n"
"    padding: 10px; /* 内边距 */\n"
"    border: 1px solid rgb(150, 150, 150); /* 边框 */\n"
"    border-top-left-radius: 5px; /* 左上角圆角 */\n"
"    border-top-right-radius: 5px; /* 右上角圆角 */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: transparent; /* 选中标签页的背景颜色 */\n"
"    color: rgb(0, 0, 0); /* 选中标签页的字体颜色 */\n"
"}\n"
"*{\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.textShow_1 = QtWidgets.QTextEdit(self.tab)
        self.textShow_1.setEnabled(False)
        self.textShow_1.setGeometry(QtCore.QRect(10, 10, 901, 271))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_1.setFont(font)
        self.textShow_1.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textShow_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textShow_1.setLineWidth(1)
        self.textShow_1.setObjectName("textShow_1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textShow_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textShow_2.setEnabled(False)
        self.textShow_2.setGeometry(QtCore.QRect(10, 10, 901, 271))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_2.setFont(font)
        self.textShow_2.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textShow_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textShow_2.setLineWidth(1)
        self.textShow_2.setObjectName("textShow_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textShow_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textShow_3.setEnabled(False)
        self.textShow_3.setGeometry(QtCore.QRect(10, 10, 901, 271))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_3.setFont(font)
        self.textShow_3.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textShow_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textShow_3.setLineWidth(1)
        self.textShow_3.setObjectName("textShow_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textShow_4 = QtWidgets.QTextEdit(self.tab_4)
        self.textShow_4.setEnabled(False)
        self.textShow_4.setGeometry(QtCore.QRect(10, 10, 901, 271))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_4.setFont(font)
        self.textShow_4.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textShow_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textShow_4.setLineWidth(1)
        self.textShow_4.setObjectName("textShow_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("margin-bottom: 5px;")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.tabWidget.raise_()
        self.frame_2 = QtWidgets.QFrame(MainUI)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 291, 641))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridFrame = QtWidgets.QFrame(self.frame_2)
        self.gridFrame.setGeometry(QtCore.QRect(0, 15, 289, 617))
        self.gridFrame.setStyleSheet("")
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame.setLineWidth(2)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.buildGranular = QtWidgets.QPushButton(self.gridFrame)
        self.buildGranular.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.buildGranular.setFont(font)
        self.buildGranular.setStyleSheet("#buildGranular{\n"
"text-align: left;\n"
"    \n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#buildGranular:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#buildGranular:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/newlybuild.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buildGranular.setIcon(icon2)
        self.buildGranular.setObjectName("buildGranular")
        self.gridLayout.addWidget(self.buildGranular, 4, 0, 1, 1)
        self.pushRh = QtWidgets.QPushButton(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushRh.setFont(font)
        self.pushRh.setStyleSheet("#pushRh{\n"
"    text-align: left;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#pushRh:hover{\n"
"icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushRh:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.pushRh.setIcon(icon2)
        self.pushRh.setObjectName("pushRh")
        self.gridLayout.addWidget(self.pushRh, 1, 0, 1, 1)
        self.pushRh_2 = QtWidgets.QPushButton(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushRh_2.setFont(font)
        self.pushRh_2.setStyleSheet("#pushRh_2{\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    text-align: left;\n"
"    border-radius:10px\n"
"}\n"
"#pushRh_2:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushRh_2:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.pushRh_2.setIcon(icon2)
        self.pushRh_2.setObjectName("pushRh_2")
        self.gridLayout.addWidget(self.pushRh_2, 8, 0, 1, 1)
        self.btnConfig = QtWidgets.QPushButton(self.gridFrame)
        self.btnConfig.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.btnConfig.setFont(font)
        self.btnConfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnConfig.setStyleSheet("#btnConfig{\n"
"text-align: left;\n"
"    \n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnConfig:hover{\n"
"    icon:url(:/images/file-settings-one_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color:transparent;\n"
"}\n"
"#btnConfig:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.btnConfig.setIcon(icon2)
        self.btnConfig.setObjectName("btnConfig")
        self.gridLayout.addWidget(self.btnConfig, 2, 0, 1, 1)
        self.help = QtWidgets.QPushButton(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.help.setFont(font)
        self.help.setStyleSheet("#help{\n"
"    background: transparent;  \n"
"    color: rgb(0, 0, 0);  \n"
"    text-align: left;\n"
"    border-radius:10px\n"
"}\n"
"#help:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#help:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.help.setIcon(icon1)
        self.help.setObjectName("help")
        self.gridLayout.addWidget(self.help, 9, 0, 1, 1)
        self.pushProblems = QtWidgets.QPushButton(self.gridFrame)
        self.pushProblems.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushProblems.setFont(font)
        self.pushProblems.setStyleSheet("#pushProblems{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#pushProblems:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushProblems:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.pushProblems.setIcon(icon2)
        self.pushProblems.setObjectName("pushProblems")
        self.gridLayout.addWidget(self.pushProblems, 7, 0, 1, 1)
        self.pushView_1 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushView_1.sizePolicy().hasHeightForWidth())
        self.pushView_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushView_1.setFont(font)
        self.pushView_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushView_1.setStyleSheet("#pushView_1{\n"
"    text-align: left;\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#pushView_1:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushView_1:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.pushView_1.setIcon(icon2)
        self.pushView_1.setObjectName("pushView_1")
        self.gridLayout.addWidget(self.pushView_1, 0, 0, 1, 1)
        self.optGranular = QtWidgets.QPushButton(self.gridFrame)
        self.optGranular.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.optGranular.setFont(font)
        self.optGranular.setStyleSheet("#optGranular{\n"
"text-align: left;\n"
"    \n"
"    background: transparent;  \n"
"    color: rgb(0, 0, 0);  \n"
"    border-radius:10px\n"
"}\n"
"#optGranular:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#optGranular:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.optGranular.setIcon(icon2)
        self.optGranular.setObjectName("optGranular")
        self.gridLayout.addWidget(self.optGranular, 5, 0, 1, 1)

        self.retranslateUi(MainUI)
        self.tabWidget.setCurrentIndex(0)
        self.optGranular.clicked.connect(MainUI.optGranularW) # type: ignore
        self.buildGranular.clicked.connect(MainUI.buildGranularW) # type: ignore
        self.pushProblems.clicked.connect(MainUI.resolveProblemsW) # type: ignore
        self.btnConfig.clicked.connect(MainUI.configGranular) # type: ignore
        self.help.clicked.connect(MainUI.helps) # type: ignore
        self.pushView_1.clicked.connect(MainUI.importView) # type: ignore
        self.resetView_1.clicked.connect(MainUI.resetInfo) # type: ignore
        self.pushRh.clicked.connect(MainUI.rhSelect) # type: ignore
        self.pushRh_2.clicked.connect(MainUI.rhResult) # type: ignore
        self.pushRh_2.clicked.connect(MainUI.rhResult) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "基于粒计算的多模态数据多粒度融合仿真系统"))
        self.resetView_1.setText(_translate("MainUI", "重置"))
        self.tip5.setToolTip(_translate("MainUI", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">导入的文件必须是.csv格式的文件</span></p></body></html>"))
        self.label_4.setText(_translate("MainUI", "问题求解层:"))
        self.tip6.setToolTip(_translate("MainUI", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">导入的文件必须是.csv格式的文件</span></p></body></html>"))
        self.label_5.setText(_translate("MainUI", "下游任务:"))
        self.textView_4.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tip3.setToolTip(_translate("MainUI", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">导入的文件必须是.csv格式的文件</span></p></body></html>"))
        self.label_2.setText(_translate("MainUI", "数据集名称:"))
        self.textView_1.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tip4.setToolTip(_translate("MainUI", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">导入的文件必须是.csv格式的文件</span></p></body></html>"))
        self.label_3.setText(_translate("MainUI", " 融合算法:"))
        self.label.setText(_translate("MainUI", "配置信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainUI", "粒结构建立"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainUI", "粒结构优化"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainUI", "求解层选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainUI", "结果分析"))
        self.label_6.setText(_translate("MainUI", "结果显示"))
        self.buildGranular.setText(_translate("MainUI", "粒结构建立"))
        self.pushRh.setText(_translate("MainUI", "融合算法导入"))
        self.pushRh_2.setText(_translate("MainUI", "融合结果分析"))
        self.btnConfig.setText(_translate("MainUI", "数据预处理"))
        self.help.setText(_translate("MainUI", "帮助文档"))
        self.pushProblems.setText(_translate("MainUI", "问题求解层选择"))
        self.pushView_1.setText(_translate("MainUI", "多模态数据导入"))
        self.optGranular.setText(_translate("MainUI", "粒结构优化"))
import image_rc
