# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ronghe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Frame_RH(object):
    def setupUi(self, Frame_RH):
        Frame_RH.setObjectName("Frame_RH")
        Frame_RH.resize(325, 276)
        Frame_RH.setStyleSheet("background-image: url(:/images/bg01_cs02.png);")
        # 禁用最大化按钮
        self.setWindowFlags(Qt.Window | Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)
        self.frame = QtWidgets.QFrame(Frame_RH)
        self.frame.setGeometry(QtCore.QRect(10, 20, 321, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalWidget = QtWidgets.QWidget(self.frame)
        self.horizontalWidget.setGeometry(QtCore.QRect(0, 174, 301, 80))
        self.horizontalWidget.setStyleSheet("")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalWidget = QtWidgets.QWidget(self.frame)
        self.verticalWidget.setGeometry(QtCore.QRect(44, 0, 231, 161))
        self.verticalWidget.setStyleSheet("")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.r2 = QtWidgets.QRadioButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.r2.setFont(font)
        self.r2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r2.setStyleSheet("background: transparent;  ")
        self.r2.setObjectName("r2")
        self.verticalLayout.addWidget(self.r2)
        self.r1 = QtWidgets.QRadioButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.r1.setFont(font)
        self.r1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r1.setStyleSheet("background: transparent;  ")
        self.r1.setObjectName("r1")
        self.r1.setChecked(True)
        self.verticalLayout.addWidget(self.r1)
        self.r3 = QtWidgets.QRadioButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.r3.setFont(font)
        self.r3.setStyleSheet("background: transparent;  ")
        self.r3.setObjectName("r3")
        self.verticalLayout.addWidget(self.r3)

        self.retranslateUi(Frame_RH)
        self.pushButton.clicked.connect(Frame_RH.ok) # type: ignore
        self.pushButton_2.clicked.connect(Frame_RH.cancel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Frame_RH)

    def retranslateUi(self, Frame_RH):
        _translate = QtCore.QCoreApplication.translate
        Frame_RH.setWindowTitle(_translate("Frame_RH", "融合算法导入"))
        self.pushButton.setText(_translate("Frame_RH", "确定"))
        self.pushButton_2.setText(_translate("Frame_RH", "取消"))
        self.r2.setText(_translate("Frame_RH", "结果融合"))
        self.r1.setText(_translate("Frame_RH", "数据融合"))
        self.r3.setText(_translate("Frame_RH", "特征融合"))
import image_rc
